-- INSERT INTO `USERS` (NAME,
--                     EMAIL,
--                     PASSWORD,
--                     CREATED_AT)
-- values ('김무건',
--         'test@naver.com',
--         '1234',
--         '20232-1-20 17:43:00');